server.port=8084
spring.threads.virtual.enabled=true
spring.jpa.properties.hibernate.default_schema=finance
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=analytics-service