#!/bin/bash
# start.sh — Build, start all services, then auto-regenerate Fluent Bit container name map
set -e
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

cd "$(dirname "$0")"

echo -e "${CYAN}╔══════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║   Finance Assistant — Start Stack        ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════╝${NC}"

# Step 1: Build & create containers (do not start yet)
echo -e "\n${YELLOW}[1/3] Building and creating containers...${NC}"
# Stop Fluent Bit first in case the stack is already running, preventing stale ingestion
docker compose stop fluent-bit > /dev/null 2>&1
docker compose up --no-start --build

# Step 2: Regenerate Fluent Bit container name map BEFORE Fluent Bit starts
echo -e "\n${YELLOW}[2/3] Generating container name map...${NC}"
LUA="observability/fluent-bit/docker_name.lua"

python3 - << 'PYEOF'
import subprocess
result = subprocess.run(['docker','ps','-a','--format','{{.ID}} {{.Names}}'], capture_output=True, text=True)
lines = result.stdout.strip().split('\n')
lua  = "-- docker_name.lua (auto-generated by start.sh)\n"
lua += "local NAMES = {\n"
for line in lines:
    parts = line.strip().split(' ', 1)
    if len(parts) == 2:
        short_id, name = parts[0][:12], parts[1].strip()
        lua += f'  ["{short_id}"] = "{name}",\n'
        print(f"  {short_id} -> {name}")
lua += "}\n"
lua += """local function resolve(cid)
    local short = string.sub(cid, 1, 12)
    return NAMES[short] or short
end
function add_container_name(tag, timestamp, record)
    local cid = string.match(tag, "docker%.(.+)")
    record["source"] = cid and resolve(cid) or "unknown"
    -- Remove Docker metadata; ClickHouse only needs 'source' and 'log'.
    -- timestamp uses DEFAULT now64() in ClickHouse.
    record["time"]   = nil
    record["stream"] = nil
    return 1, timestamp, record
end
"""
with open('observability/fluent-bit/docker_name.lua', 'w') as f:
    f.write(lua)
PYEOF

# Step 3: Start all services now that the map is ready
echo -e "\n${YELLOW}[3/3] Starting full stack...${NC}"
docker compose up -d

echo -e "\n${GREEN}Stack is up! Fluent Bit is capturing logs with correct names.${NC}"
echo -e "  Finance App  → http://localhost:8000"
echo -e "  Dev Console  → http://localhost:8000/dev.html"
echo -e "  Grafana      → http://localhost:3000  (admin/admin)"
echo -e "  Prometheus   → http://localhost:9090"
echo -e "  ClickHouse   → http://localhost:8123/play"
