apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse-ds
    access: proxy
    editable: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: observability_logs
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: clickhouse
