apiVersion: 1

datasources:
  - name: Zipkin
    type: zipkin
    access: proxy
    url: http://zipkin:9411
    isDefault: false
    uid: zipkin-ds
    jsonData:
      tracesToLogsV2:
        datasourceUid: clickhouse-ds
        filterByTraceID: false
        filterBySpanID: false
        tags: []
        customQuery: true
        query: 'SELECT timestamp, message, level FROM default.logs WHERE trace_id = ''${__trace.traceId}'''
      nodeGraph:
        enabled: true
