CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS finance;
CREATE SCHEMA IF NOT EXISTS groups;
CREATE SCHEMA IF NOT EXISTS activity;

GRANT USAGE ON SCHEMA auth TO PUBLIC;
GRANT USAGE ON SCHEMA finance TO PUBLIC;
GRANT USAGE ON SCHEMA groups TO PUBLIC;
GRANT USAGE ON SCHEMA activity TO PUBLIC;
