-- docker_name.lua (auto-generated by start.sh)
local NAMES = {
  ["920a43e8956d"] = "frontend",
  ["27752c310127"] = "api-gateway",
  ["57c6458d2b01"] = "ocr-parser-service",
  ["85ac6b9e4dae"] = "analytics-service",
  ["c1617a9a5eed"] = "auth-service",
  ["f4040b3c3fb3"] = "upsert-service",
  ["dbabc541e9b5"] = "grafana",
  ["48dc59436d3b"] = "fluent-bit",
  ["c4e1d965880c"] = "postgres-db",
  ["a5cdc6103423"] = "clickhouse",
  ["7137867e3571"] = "prometheus",
  ["6b18d8ccd88b"] = "dev-clickhouse-server",
}
local function resolve(cid)
    local short = string.sub(cid, 1, 12)
    return NAMES[short] or short
end
function add_container_name(tag, timestamp, record)
    local cid = string.match(tag, "docker%.(.+)")
    record["source"] = cid and resolve(cid) or "unknown"
    -- Remove Docker metadata; ClickHouse only needs 'source' and 'log'.
    -- timestamp uses DEFAULT now64() in ClickHouse.
    record["time"]   = nil
    record["stream"] = nil
    return 1, timestamp, record
end
