spring.application.name=auth-service
server.port=8082
spring.jpa.properties.hibernate.default_schema=auth

# JWT Configuration
jwt.secret=my-super-secret-key-that-is-long-enough-for-hmac-sha256-algorithm-and-very-secure
jwt.expiration=86400000

# Logging Configuration
logging.level.com.pm.authservice=DEBUG
logging.level.org.springframework=DEBUG
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=auth-service